// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjlCwC9-8b7gnjFmzoR3_sG4W3tbWNUsk',
    appId: '1:578115042061:web:17a23a0d234c7273cece44',
    messagingSenderId: '578115042061',
    projectId: 'bright-wave-ioj9xl',
    authDomain: 'bright-wave-ioj9xl.firebaseapp.com',
    storageBucket: 'bright-wave-ioj9xl.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1UoclvtOdy8Eni_U1L4rrCJtXz0WXMbI',
    appId: '1:578115042061:android:06974666b876834fcece44',
    messagingSenderId: '578115042061',
    projectId: 'bright-wave-ioj9xl',
    storageBucket: 'bright-wave-ioj9xl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5wvjLYuHw3EOxre6bTGGen0BjgJFPZPk',
    appId: '1:578115042061:ios:2a61da49dcea5cc2cece44',
    messagingSenderId: '578115042061',
    projectId: 'bright-wave-ioj9xl',
    storageBucket: 'bright-wave-ioj9xl.firebasestorage.app',
    iosBundleId: 'com.mycompany.brightwave',
  );

}