import 'package:flutter/material.dart';

String ffTranslate(
  BuildContext context,
  String source, {
  Map<String, String>? replacements,
}) {
  final locale = Localizations.maybeLocaleOf(context);
  final languageCode =
      (locale?.languageCode.isNotEmpty ?? false) ? locale!.languageCode : 'en';
  return ffTranslateForCode(
    languageCode,
    source,
    replacements: replacements,
  );
}

String ffTranslateForCode(
  String languageCode,
  String source, {
  Map<String, String>? replacements,
}) {
  final normalizedCode = languageCode.toLowerCase().split('_').first;
  final translated = _ffTranslations[normalizedCode]?[source] ?? source;
  if (replacements == null || replacements.isEmpty) {
    return translated;
  }

  var output = translated;
  replacements.forEach((key, value) {
    output = output.replaceAll('{$key}', value);
  });
  return output;
}

String ffLanguageName(BuildContext context, String languageCode) {
  switch (languageCode.toLowerCase()) {
    case 'en':
      return ffTranslate(context, 'English');
    case 'es':
      return ffTranslate(context, 'Spanish');
    case 'de':
      return ffTranslate(context, 'German');
    case 'fr':
      return ffTranslate(context, 'French');
    default:
      return languageCode.toUpperCase();
  }
}

const Map<String, Map<String, String>> _ffTranslations = {
  'en': {
    'Berichten': 'Messages',
    'Groeps chat': 'Group chat',
    'Chat': 'Chat',
    'Jou bericht': 'Your message',
    'Alle events': 'All events',
    'In de buurt': 'Nearby',
    'Niet missen': 'Do not miss',
    'Uitnodiging': 'Invitation',
    'Registrate': 'Register',
    'Scanner': 'Scanner',
    'T-shirt': 'T-shirt',
    'Accessoires': 'Accessories',
    'Stickers': 'Stickers',
    'Sticker': 'Sticker',
    '{count} van de {total} producten': '{count} of {total} products',
    'Best verkocht': 'Best selling',
    'Alles': 'All',
    'Mokken': 'Mugs',
    'Kon producten niet laden': 'Could not load products',
    'Geen producten gevonden': 'No products found',
    'Search products': 'Search products',
    'Type to search products': 'Type to search products',
    'No results for "{query}"': 'No results for "{query}"',
    'Filter by name': 'Filter by name',
    'Filter by price (e.g., 20 or 20-50)': 'Filter by price (e.g., 20 or 20-50)',
    'Switch to price filter': 'Switch to price filter',
    'Switch to name filter': 'Switch to name filter',
    'Type a product name': 'Type a product name',
    'Type a price or range, e.g. 25 or 20-50': 'Type a price or range, e.g. 25 or 20-50',
    'No products match your filter': 'No products match your filter',
    'Shared Media': 'Shared Media',
    'Images': 'Images',
    'Audio': 'Audio',
    'No images shared': 'No images shared',
    'Images shared in this chat will appear here': 'Images shared in this chat will appear here',
    'No audio shared': 'No audio shared',
    'Voice messages shared in this chat will appear here': 'Voice messages shared in this chat will appear here',
    'Unable to load media': 'Unable to load media',
    'Yesterday': 'Yesterday',
    'days ago': 'days ago',
    'Unknown': 'Unknown',
    'Search coming soon': 'Search coming soon',
    'Mute Notifications': 'Mute Notifications',
    'Mute notifications coming soon': 'Mute notifications coming soon',
  },
  'es': {
    'Scanner': 'Escáner',
    'T-shirt': 'Camiseta',
    'Accessoires': 'Accesorios',
    'Stickers': 'Pegatinas',
    'Sticker': 'Pegatina',
    '{count} van de {total} producten': '{count} de {total} productos',
    'Best verkocht': 'Más vendidos',
    'Alles': 'Todo',
    'Mokken': 'Tazas',
    'Kon producten niet laden': 'No se pudieron cargar los productos',
    'Geen producten gevonden': 'No se encontraron productos',
    'Search products': 'Buscar productos',
    'Type to search products': 'Escribe para buscar productos',
    'No results for "{query}"': 'Sin resultados para "{query}"',
    'Filter by name': 'Filtrar por nombre',
    'Filter by price (e.g., 20 or 20-50)': 'Filtrar por precio (ej., 20 o 20-50)',
    'Switch to price filter': 'Cambiar a filtro de precio',
    'Switch to name filter': 'Cambiar a filtro de nombre',
    'Type a product name': 'Escribe un nombre de producto',
    'Type a price or range, e.g. 25 or 20-50': 'Escribe un precio o rango, ej. 25 o 20-50',
    'No products match your filter': 'Ningún producto coincide con tu filtro',
    'Back': 'Atrás',
    'Profile': 'Perfil',
    'Account': 'Cuenta',
    'Support & Legal': 'Soporte y legal',
    'My Profile': 'Mi perfil',
    'Tickets': 'Entradas',
    'Interests': 'Intereses',
    'Settings': 'Configuración',
    'Dark Mode / Light Mode': 'Modo oscuro / Modo claro',
    'Language': 'Idioma',
    'About Us': 'Sobre nosotros',
    'Log Out': 'Cerrar sesión',
    'DigitalRadicalz Member': 'Miembro de DigitalRadicalz',
    'Unknown User': 'Usuario desconocido',
    'No email linked': 'Sin correo vinculado',
    'Select language': 'Seleccionar idioma',
    'Select a language': 'Selecciona un idioma',
    'System default': 'Predeterminado del sistema',
    'English': 'Inglés',
    'Spanish': 'Español',
    'German': 'Alemán',
    'French': 'Francés',
    'Language ({language})': 'Idioma ({language})',
    'Search....': 'Buscar....',
    'Search Post..': 'Buscar publicación..',
    'Search': 'Buscar',
    'search for user': 'buscar usuario',
    'Search users...': 'Buscar usuarios...',
    'Search members...': 'Buscar miembros...',
    'Add a comment': 'Añadir un comentario',
    'Enter your email': 'Introduce tu correo',
    'Enter your name': 'Introduce tu nombre',
    'Enter your text': 'Introduce tu texto',
    'Select Method': 'Seleccionar método',
    'Select payment ': 'Seleccionar pago ',
    'Enter code': 'Introduce el código',
    'Add a title to your group': 'Añade un título a tu grupo',
    'Describe your Group': 'Describe tu grupo',
    'Describe your group...': 'Describe tu grupo...',
    'Add a title to your post': 'Añade un título a tu publicación',
    'Describe your post': 'Describe tu publicación',
    'Continue': 'Continuar',
    'Create Group': 'Crear grupo',
    'Create group': 'Crear grupo',
    'Group title required': 'Se requiere título del grupo',
    'Group created': 'Grupo creado',
    'Failed to create group. Please try again.':
        'No se pudo crear el grupo. Inténtalo de nuevo.',
    'Enter group name': 'Introduce el nombre del grupo',
    'Enter new group name': 'Introduce un nuevo nombre de grupo',
    'Type a message...': 'Escribe un mensaje...',
    'Jou bericht': 'Tu mensaje',
    'Save': 'Guardar',
    'Save Changes': 'Guardar cambios',
    'Your full name': 'Tu nombre completo',
    'Street name': 'Nombre de la calle',
    'No.': 'N.º',
    'Town name': 'Nombre de la ciudad',
    'MM/DD/YYYY': 'MM/DD/AAAA',
    'Password': 'Contraseña',
    'Email': 'Correo electrónico',
    'Name': 'Nombre',
    'Confirm Password': 'Confirmar contraseña',
    'Member': 'Miembro',
    'Login': 'Iniciar sesión',
    'Log in': 'Iniciar sesión',
    'Go to Login': 'Ir a iniciar sesión',
    'NEXT': 'SIGUIENTE',
    'Next': 'Siguiente',
    'View in account': 'Ver en cuenta',
    'Back to home': 'Volver al inicio',
    'Order again': 'Pedir de nuevo',
    'Add To Cart': 'Añadir al carrito',
    'Make payment': 'Realizar pago',
    'Place Order': 'Realizar pedido',
    'Terms': 'Términos',
    'By placing an order you agree to our ':
        'Al realizar un pedido aceptas nuestros ',
    'and agree to the terms and conditions\nThese products are delivered online to my email address example@fancee.com':
        'y aceptas los términos y condiciones\nEstos productos se entregan en línea a mi correo electrónico example@fancee.com',
    'Conditions': 'Condiciones',
    'And': 'y',
    ' And ': ' Y ',
    ' Log in': ' Iniciar sesión',
    'Already have an account?': '¿Ya tienes una cuenta?',
    'Go Back': 'Volver',
    'Members': 'Miembros',
    ' Members': ' Miembros',
    ' for': ' para',
    'left to order tickets ': ' restantes para pedir entradas ',
    ' left to order tickets ': ' restantes para pedir entradas ',
    'for': 'para',
    'I place an order with a total of ': 'Realizo un pedido por un total de ',
    'Left to order tickets for\nExample festival':
        'Entradas restantes para\nfestival de ejemplo',
    '\nContact: \n': '\nContacto: \n',
    ' + ': ' + ',
    'x ': 'x ',
    'All tickets deleted.': 'Todas las entradas eliminadas.',
    'Delete all tickets?': '¿Eliminar todas las entradas?',
    'Delete all': 'Eliminar todo',
    'Clear all': 'Borrar todo',
    'No tickets yet': 'Aún no tienes entradas',
    'Delete one ticket?': '¿Eliminar una entrada?',
    'Delete': 'Eliminar',
    'Cancel': 'Cancelar',
    'Error': 'Error',
    'Comment deleted': 'Comentario eliminado',
    'Delete comment?': '¿Eliminar comentario?',
    'Failed to delete comment': 'No se pudo eliminar el comentario',
    'Failed to delete ticket': 'No se pudo eliminar la entrada',
    'Failed to delete tickets': 'No se pudieron eliminar las entradas',
    'This action cannot be undone.': 'Esta acción no se puede deshacer.',
    'Invalid file format': 'Formato de archivo no válido',
    'Retry': 'Reintentar',
    'News': 'Noticias',
    'Events': 'Eventos',
    'Products': 'Productos',
    'Media': 'Medios',
    'Courses': 'Cursos',
    'Course': 'Curso',
    'Workshop': 'Taller',
    'Training': 'Entrenamiento',
    'Podcast': 'Pódcast',
    'Community chat': 'Chat de comunidad',
    'Berichten': 'Mensajes',
    'Groeps chat': 'Chat grupal',
    'Interest': 'Interés',
    'Purpose': 'Propósito',
    'Role': 'Rol',
    'Join': 'Unirse',
    'Leave': 'Salir',
    'Create a Post': 'Crear una publicación',
    'Posts': 'Publicaciones',
    'Published by: ': 'Publicado por: ',
    'Posted at:': 'Publicado a las:',
    'Bio: ': 'Biografía: ',
    'Contact: ': 'Contacto: ',
    'Tel: ': 'Tel: ',
    'Follow': 'Seguir',
    'Unfollow': 'Dejar de seguir',
    'Use Language of the phone': 'Usar el idioma del teléfono',
    'Ticketaccount': 'Cuenta de tickets',
    'Connect ticketaccount': 'Conectar cuenta de tickets',
    'Send code': 'Enviar código',
    'example@fanceesoftware.com': 'ejemplo@fanceesoftware.com',
    'Event unavailable': 'Evento no disponible',
    'Date unavailable': 'Fecha no disponible',
    'Location unavailable': 'Ubicación no disponible',
    'name@example.com': 'nombre@ejemplo.com',
    'Password must be at least 6 characters.':
        'La contraseña debe tener al menos 6 caracteres.',
    'Password reset email sent':
        'Se ha enviado el correo para restablecer la contraseña',
    'Describe your group purpose, audience, and vibe':
        'Describe el propósito, la audiencia y el estilo de tu grupo',
    'Drag to resize': 'Arrastra para redimensionar',
    'Drag handle: drag vertically to resize agenda panel':
        'Control de arrastre: arrastra verticalmente para redimensionar el panel de agenda',
    'Error: \${e.message!}': 'Error: \${e.message!}',
    'Failed to delete comment: \$e': 'No se pudo eliminar el comentario: \$e',
    'Failed to delete ticket: \$e': 'No se pudo eliminar la entrada: \$e',
    'Failed to delete tickets: \$e':
        'No se pudieron eliminar las entradas: \$e',
    'Invalid file format: \${mime(filePath)}':
        'Formato de archivo no válido: \${mime(filePath)}',
    '+1 555 123 4567': '+1 555 123 4567',
    '••••••••••••': '••••••••••••',
    'No messages yet': 'Aún no hay mensajes',
    'Error playing video': 'Error al reproducir video',
    'Loading': 'Cargando',
    'Chat': 'Chat',
    'Shared Media': 'Medios compartidos',
    'Images': 'Imágenes',
    'Audio': 'Audio',
    'No images shared': 'Sin imágenes compartidas',
    'Images shared in this chat will appear here': 'Las imágenes compartidas en este chat aparecerán aquí',
    'No audio shared': 'Sin audio compartido',
    'Voice messages shared in this chat will appear here': 'Los mensajes de voz compartidos en este chat aparecerán aquí',
    'Unable to load media': 'No se pueden cargar los medios',
    'Yesterday': 'Ayer',
    'days ago': 'días atrás',
    'Unknown': 'Desconocido',
    'Search coming soon': 'Búsqueda próximamente',
    'Mute Notifications': 'Silenciar notificaciones',
    'Mute notifications coming soon': 'Silenciar notificaciones próximamente',
  },
  'de': {
    'Scanner': 'Scanner',
    'T-shirt': 'T-Shirt',
    'Accessoires': 'Zubehör',
    'Stickers': 'Aufkleber',
    'Sticker': 'Aufkleber',
    '{count} van de {total} producten': '{count} von {total} Produkten',
    'Best verkocht': 'Meistverkauft',
    'Alles': 'Alle',
    'Mokken': 'Tassen',
    'Kon producten niet laden': 'Produkte konnten nicht geladen werden',
    'Geen producten gevonden': 'Keine Produkte gefunden',
    'Search products': 'Produkte suchen',
    'Type to search products': 'Tippen Sie, um Produkte zu suchen',
    'No results for "{query}"': 'Keine Ergebnisse für "{query}"',
    'Filter by name': 'Nach Name filtern',
    'Filter by price (e.g., 20 or 20-50)': 'Nach Preis filtern (z.B. 20 oder 20-50)',
    'Switch to price filter': 'Zu Preisfilter wechseln',
    'Switch to name filter': 'Zu Namensfilter wechseln',
    'Type a product name': 'Produktname eingeben',
    'Type a price or range, e.g. 25 or 20-50': 'Preis oder Bereich eingeben, z.B. 25 oder 20-50',
    'No products match your filter': 'Keine Produkte entsprechen Ihrem Filter',
    'Back': 'Zurück',
    'Profile': 'Profil',
    'Account': 'Konto',
    'Support & Legal': 'Support & Rechtliches',
    'My Profile': 'Mein Profil',
    'Tickets': 'Tickets',
    'Interests': 'Interessen',
    'Settings': 'Einstellungen',
    'Dark Mode / Light Mode': 'Dunkelmodus / Hellmodus',
    'Language': 'Sprache',
    'About Us': 'Über uns',
    'Log Out': 'Abmelden',
    'DigitalRadicalz Member': 'DigitalRadicalz-Mitglied',
    'Unknown User': 'Unbekannter Benutzer',
    'No email linked': 'Keine E-Mail verknüpft',
    'Select language': 'Sprache auswählen',
    'Select a language': 'Wähle eine Sprache',
    'System default': 'Systemstandard',
    'English': 'Englisch',
    'Spanish': 'Spanisch',
    'German': 'Deutsch',
    'French': 'Französisch',
    'Language ({language})': 'Sprache ({language})',
    'Search....': 'Suchen....',
    'Search Post..': 'Beitrag suchen..',
    'Search': 'Suchen',
    'search for user': 'Nutzer suchen',
    'Search users...': 'Nutzer suchen...',
    'Search members...': 'Mitglieder suchen...',
    'Add a comment': 'Kommentar hinzufügen',
    'Enter your email': 'E-Mail eingeben',
    'Enter your name': 'Name eingeben',
    'Enter your text': 'Text eingeben',
    'Select Method': 'Methode auswählen',
    'Select payment ': 'Zahlung auswählen ',
    'Enter code': 'Code eingeben',
    'Add a title to your group': 'Füge deiner Gruppe einen Titel hinzu',
    'Describe your Group': 'Beschreibe deine Gruppe',
    'Describe your group...': 'Beschreibe deine Gruppe...',
    'Add a title to your post': 'Füge deinem Beitrag einen Titel hinzu',
    'Describe your post': 'Beschreibe deinen Beitrag',
    'Continue': 'Weiter',
    'Create Group': 'Gruppe erstellen',
    'Create group': 'Gruppe erstellen',
    'Group title required': 'Gruppentitel erforderlich',
    'Group created': 'Gruppe erstellt',
    'Failed to create group. Please try again.':
        'Gruppe konnte nicht erstellt werden. Bitte erneut versuchen.',
    'Enter group name': 'Gruppennamen eingeben',
    'Enter new group name': 'Neuen Gruppennamen eingeben',
    'Type a message...': 'Nachricht eingeben...',
    'Jou bericht': 'Deine Nachricht',
    'Save': 'Speichern',
    'Save Changes': 'Änderungen speichern',
    'Your full name': 'Dein vollständiger Name',
    'Street name': 'Straßenname',
    'No.': 'Nr.',
    'Town name': 'Stadtname',
    'MM/DD/YYYY': 'MM/TT/JJJJ',
    'Password': 'Passwort',
    'Email': 'E-Mail',
    'Name': 'Name',
    'Confirm Password': 'Passwort bestätigen',
    'Member': 'Mitglied',
    'Login': 'Anmelden',
    'Log in': 'Anmelden',
    'Go to Login': 'Zum Login',
    'NEXT': 'WEITER',
    'Next': 'Weiter',
    'View in account': 'Im Konto ansehen',
    'Back to home': 'Zur Startseite',
    'Order again': 'Erneut bestellen',
    'Add To Cart': 'In den Warenkorb',
    'Make payment': 'Bezahlen',
    'Place Order': 'Bestellung aufgeben',
    'Terms': 'Bedingungen',
    'By placing an order you agree to our ':
        'Mit einer Bestellung stimmst du unseren ',
    'and agree to the terms and conditions\nThese products are delivered online to my email address example@fancee.com':
        'zu und akzeptierst die Geschäftsbedingungen\nDiese Produkte werden online an meine E-Mail-Adresse example@fancee.com geliefert',
    'Conditions': 'Konditionen',
    'And': 'und',
    ' And ': ' Und ',
    ' Log in': ' Anmelden',
    'Already have an account?': 'Hast du bereits ein Konto?',
    'Go Back': 'Zurück',
    'Members': 'Mitglieder',
    ' Members': ' Mitglieder',
    ' for': ' für',
    'left to order tickets ': ' verbleibend, um Tickets zu bestellen ',
    ' left to order tickets ': ' verbleibend, um Tickets zu bestellen ',
    'for': 'für',
    'I place an order with a total of ':
        'Ich gebe eine Bestellung mit insgesamt ',
    'Left to order tickets for\nExample festival':
        'Verbleibende Tickets für\nBeispielfestival',
    '\nContact: \n': '\nKontakt: \n',
    ' + ': ' + ',
    'x ': 'x ',
    'All tickets deleted.': 'Alle Tickets gelöscht.',
    'Delete all tickets?': 'Alle Tickets löschen?',
    'Delete all': 'Alle löschen',
    'Clear all': 'Alle entfernen',
    'No tickets yet': 'Noch keine Tickets',
    'Delete one ticket?': 'Ein Ticket löschen?',
    'Delete': 'Löschen',
    'Cancel': 'Abbrechen',
    'Error': 'Fehler',
    'Comment deleted': 'Kommentar gelöscht',
    'Delete comment?': 'Kommentar löschen?',
    'Failed to delete comment': 'Kommentar konnte nicht gelöscht werden',
    'Failed to delete ticket': 'Ticket konnte nicht gelöscht werden',
    'Failed to delete tickets': 'Tickets konnten nicht gelöscht werden',
    'This action cannot be undone.':
        'Diese Aktion kann nicht rückgängig gemacht werden.',
    'Invalid file format': 'Ungültiges Dateiformat',
    'Retry': 'Wiederholen',
    'News': 'Nachrichten',
    'Events': 'Veranstaltungen',
    'Products': 'Produkte',
    'Media': 'Medien',
    'Courses': 'Kurse',
    'Course': 'Kurs',
    'Workshop': 'Workshop',
    'Training': 'Training',
    'Podcast': 'Podcast',
    'Community chat': 'Community-Chat',
    'Berichten': 'Nachrichten',
    'Groeps chat': 'Gruppenchat',
    'Interest': 'Interesse',
    'Purpose': 'Zweck',
    'Role': 'Rolle',
    'Join': 'Beitreten',
    'Leave': 'Verlassen',
    'Create a Post': 'Beitrag erstellen',
    'Posts': 'Beiträge',
    'Published by: ': 'Veröffentlicht von: ',
    'Posted at:': 'Veröffentlicht um:',
    'Bio: ': 'Bio: ',
    'Contact: ': 'Kontakt: ',
    'Tel: ': 'Tel: ',
    'Follow': 'Folgen',
    'Unfollow': 'Entfolgen',
    'Use Language of the phone': 'Sprache des Telefons verwenden',
    'Ticketaccount': 'Ticketkonto',
    'Connect ticketaccount': 'Ticketkonto verbinden',
    'Send code': 'Code senden',
    'Event unavailable': 'Ereignis nicht verfügbar',
    'Date unavailable': 'Datum nicht verfügbar',
    'Location unavailable': 'Ort nicht verfügbar',
    'name@example.com': 'name@beispiel.com',
    'Password must be at least 6 characters.':
        'Das Passwort muss mindestens 6 Zeichen lang sein.',
    'Password reset email sent':
        'E-Mail zum Zurücksetzen des Passworts wurde gesendet',
    'Describe your group purpose, audience, and vibe':
        'Beschreibe den Zweck, die Zielgruppe und die Stimmung deiner Gruppe',
    'Drag to resize': 'Zum Ändern der Größe ziehen',
    'Drag handle: drag vertically to resize agenda panel':
        'Ziehgriff: vertikal ziehen, um das Agenda-Panel zu vergrößern oder zu verkleinern',
    'Error: \${e.message!}': 'Fehler: \${e.message!}',
    'Failed to delete comment: \$e':
        'Kommentar konnte nicht gelöscht werden: \$e',
    'Failed to delete ticket: \$e': 'Ticket konnte nicht gelöscht werden: \$e',
    'Failed to delete tickets: \$e':
        'Tickets konnten nicht gelöscht werden: \$e',
    'Invalid file format: \${mime(filePath)}':
        'Ungültiges Dateiformat: \${mime(filePath)}',
    '+1 555 123 4567': '+1 555 123 4567',
    '••••••••••••': '••••••••••••',
    'No messages yet': 'Noch keine Nachrichten',
    'Error playing video': 'Fehler beim Abspielen des Videos',
    'Loading': 'Laden',
    'Chat': 'Chat',
    'Shared Media': 'Geteilte Medien',
    'Images': 'Bilder',
    'Audio': 'Audio',
    'No images shared': 'Keine Bilder geteilt',
    'Images shared in this chat will appear here': 'In diesem Chat geteilte Bilder erscheinen hier',
    'No audio shared': 'Kein Audio geteilt',
    'Voice messages shared in this chat will appear here': 'In diesem Chat geteilte Sprachnachrichten erscheinen hier',
    'Unable to load media': 'Medien können nicht geladen werden',
    'Yesterday': 'Gestern',
    'days ago': 'Tagen',
    'Unknown': 'Unbekannt',
    'Search coming soon': 'Suche kommt bald',
    'Mute Notifications': 'Benachrichtigungen stummschalten',
    'Mute notifications coming soon': 'Benachrichtigungen stummschalten kommt bald',
  },
  'fr': {
    'Scanner': 'Scanner',
    'T-shirt': 'T-shirt',
    'Accessoires': 'Accessoires',
    'Stickers': 'Autocollants',
    'Sticker': 'Autocollant',
    '{count} van de {total} producten': '{count} sur {total} produits',
    'Best verkocht': 'Meilleures ventes',
    'Alles': 'Tout',
    'Mokken': 'Tasses',
    'Kon producten niet laden': 'Impossible de charger les produits',
    'Geen producten gevonden': 'Aucun produit trouvé',
    'Search products': 'Rechercher des produits',
    'Type to search products': 'Tapez pour rechercher des produits',
    'No results for "{query}"': 'Aucun résultat pour "{query}"',
    'Filter by name': 'Filtrer par nom',
    'Filter by price (e.g., 20 or 20-50)': 'Filtrer par prix (ex., 20 ou 20-50)',
    'Switch to price filter': 'Passer au filtre de prix',
    'Switch to name filter': 'Passer au filtre de nom',
    'Type a product name': 'Tapez un nom de produit',
    'Type a price or range, e.g. 25 or 20-50': 'Tapez un prix ou une fourchette, ex. 25 ou 20-50',
    'No products match your filter': 'Aucun produit ne correspond à votre filtre',
    'Back': 'Retour',
    'Profile': 'Profil',
    'Account': 'Compte',
    'Support & Legal': 'Support et légal',
    'My Profile': 'Mon profil',
    'Tickets': 'Billets',
    'Interests': 'Intérêts',
    'Settings': 'Paramètres',
    'Dark Mode / Light Mode': 'Mode sombre / Mode clair',
    'Language': 'Langue',
    'About Us': 'À propos',
    'Log Out': 'Se déconnecter',
    'DigitalRadicalz Member': 'Membre DigitalRadicalz',
    'Unknown User': 'Utilisateur inconnu',
    'No email linked': 'Aucun e-mail lié',
    'Select language': 'Choisir la langue',
    'Select a language': 'Choisir une langue',
    'System default': 'Langue du système',
    'English': 'Anglais',
    'Spanish': 'Espagnol',
    'German': 'Allemand',
    'French': 'Français',
    'Language ({language})': 'Langue ({language})',
    'Search....': 'Rechercher....',
    'Search Post..': 'Rechercher un post..',
    'Search': 'Rechercher',
    'search for user': 'rechercher un utilisateur',
    'Search users...': 'Rechercher des utilisateurs...',
    'Search members...': 'Rechercher des membres...',
    'Add a comment': 'Ajouter un commentaire',
    'Enter your email': 'Entrez votre e-mail',
    'Enter your name': 'Entrez votre nom',
    'Enter your text': 'Entrez votre texte',
    'Select Method': 'Sélectionner une méthode',
    'Select payment ': 'Sélectionner le paiement ',
    'Enter code': 'Entrer le code',
    'Add a title to your group': 'Ajoutez un titre à votre groupe',
    'Describe your Group': 'Décrivez votre groupe',
    'Describe your group...': 'Décrivez votre groupe...',
    'Add a title to your post': 'Ajoutez un titre à votre publication',
    'Describe your post': 'Décrivez votre publication',
    'Continue': 'Continuer',
    'Create Group': 'Créer un groupe',
    'Create group': 'Créer un groupe',
    'Group title required': 'Titre du groupe requis',
    'Group created': 'Groupe créé',
    'Failed to create group. Please try again.':
        'Impossible de créer le groupe. Veuillez réessayer.',
    'Enter group name': 'Entrer le nom du groupe',
    'Enter new group name': 'Entrer un nouveau nom de groupe',
    'Type a message...': 'Écrire un message...',
    'Jou bericht': 'Votre message',
    'Save': 'Enregistrer',
    'Save Changes': 'Enregistrer les modifications',
    'Your full name': 'Votre nom complet',
    'Street name': 'Nom de la rue',
    'No.': 'N°',
    'Town name': 'Nom de la ville',
    'MM/DD/YYYY': 'MM/JJ/AAAA',
    'Password': 'Mot de passe',
    'Email': 'E-mail',
    'Name': 'Nom',
    'Confirm Password': 'Confirmer le mot de passe',
    'Member': 'Membre',
    'Login': 'Connexion',
    'Log in': 'Connexion',
    'Go to Login': 'Aller à la connexion',
    'NEXT': 'SUIVANT',
    'Next': 'Suivant',
    'View in account': 'Voir dans le compte',
    'Back to home': 'Retour à l’accueil',
    'Order again': 'Commander à nouveau',
    'Add To Cart': 'Ajouter au panier',
    'Make payment': 'Effectuer le paiement',
    'Place Order': 'Passer la commande',
    'Terms': 'Termes',
    'By placing an order you agree to our ':
        'En passant une commande, vous acceptez nos ',
    'and agree to the terms and conditions\nThese products are delivered online to my email address example@fancee.com':
        'et acceptez les termes et conditions\nCes produits sont livrés en ligne à mon adresse e-mail example@fancee.com',
    'Conditions': 'Conditions',
    'And': 'et',
    ' And ': ' Et ',
    ' Log in': ' Connexion',
    'Already have an account?': 'Vous avez déjà un compte ?',
    'Go Back': 'Retour',
    'Members': 'Membres',
    ' Members': ' Membres',
    ' for': ' pour',
    'left to order tickets ': ' restants pour commander des billets ',
    ' left to order tickets ': ' restants pour commander des billets ',
    'for': 'pour',
    'I place an order with a total of ':
        'Je passe une commande pour un total de ',
    'Left to order tickets for\nExample festival':
        'Billets restants pour\nfestival exemple',
    '\nContact: \n': '\nContact : \n',
    ' + ': ' + ',
    'x ': 'x ',
    'All tickets deleted.': 'Tous les billets ont été supprimés.',
    'Delete all tickets?': 'Supprimer tous les billets ?',
    'Delete all': 'Tout supprimer',
    'Clear all': 'Tout effacer',
    'No tickets yet': 'Aucun billet pour le moment',
    'Delete one ticket?': 'Supprimer un billet ?',
    'Delete': 'Supprimer',
    'Cancel': 'Annuler',
    'Error': 'Erreur',
    'Comment deleted': 'Commentaire supprimé',
    'Delete comment?': 'Supprimer le commentaire ?',
    'Failed to delete comment': 'Échec de la suppression du commentaire',
    'Failed to delete ticket': 'Échec de la suppression du billet',
    'Failed to delete tickets': 'Échec de la suppression des billets',
    'This action cannot be undone.': 'Cette action est irréversible.',
    'Invalid file format': 'Format de fichier invalide',
    'Retry': 'Réessayer',
    'News': 'Actualités',
    'Events': 'Événements',
    'Products': 'Produits',
    'Media': 'Médias',
    'Courses': 'Cours',
    'Course': 'Cours',
    'Workshop': 'Atelier',
    'Training': 'Formation',
    'Podcast': 'Podcast',
    'Community chat': 'Chat de communauté',
    'Berichten': 'Messages',
    'Groeps chat': 'Chat de groupe',
    'Interest': 'Intérêt',
    'Purpose': 'Objectif',
    'Role': 'Rôle',
    'Join': 'Rejoindre',
    'Leave': 'Quitter',
    'Create a Post': 'Créer une publication',
    'Posts': 'Publications',
    'Published by: ': 'Publié par : ',
    'Posted at:': 'Publié à :',
    'Bio: ': 'Bio : ',
    'Contact: ': 'Contact : ',
    'Tel: ': 'Tél. : ',
    'Follow': 'Suivre',
    'Unfollow': 'Ne plus suivre',
    'Use Language of the phone': 'Utiliser la langue du téléphone',
    'Ticketaccount': 'Compte ticket',
    'Connect ticketaccount': 'Connecter le compte ticket',
    'Send code': 'Envoyer le code',
    'Event unavailable': 'Événement indisponible',
    'Date unavailable': 'Date indisponible',
    'Location unavailable': 'Lieu indisponible',
    'name@example.com': 'nom@exemple.com',
    'Password must be at least 6 characters.':
        'Le mot de passe doit comporter au moins 6 caractères.',
    'Password reset email sent':
        'E-mail de réinitialisation du mot de passe envoyé',
    'Describe your group purpose, audience, and vibe':
        'Décrivez l’objectif, le public et l’ambiance de votre groupe',
    'Drag to resize': 'Faites glisser pour redimensionner',
    'Drag handle: drag vertically to resize agenda panel':
        'Poignée de glissement : faites glisser verticalement pour redimensionner le panneau agenda',
    'Error: \${e.message!}': 'Erreur : \${e.message!}',
    'Failed to delete comment: \$e':
        'Échec de la suppression du commentaire : \$e',
    'Failed to delete ticket: \$e': 'Échec de la suppression du billet : \$e',
    'Failed to delete tickets: \$e':
        'Échec de la suppression des billets : \$e',
    'Invalid file format: \${mime(filePath)}':
        'Format de fichier invalide : \${mime(filePath)}',
    '+1 555 123 4567': '+1 555 123 4567',
    '••••••••••••': '••••••••••••',
    'No messages yet': 'Aucun message pour le moment',
    'Error playing video': 'Erreur de lecture de la vidéo',
    'Loading': 'Chargement',
    'Chat': 'Discussion',
    'Shared Media': 'Médias partagés',
    'Images': 'Images',
    'Audio': 'Audio',
    'No images shared': 'Aucune image partagée',
    'Images shared in this chat will appear here': 'Les images partagées dans ce chat apparaîtront ici',
    'No audio shared': 'Aucun audio partagé',
    'Voice messages shared in this chat will appear here': 'Les messages vocaux partagés dans ce chat apparaîtront ici',
    'Unable to load media': 'Impossible de charger les médias',
    'Yesterday': 'Hier',
    'days ago': 'jours',
    'Unknown': 'Inconnu',
    'Search coming soon': 'Recherche bientôt disponible',
    'Mute Notifications': 'Désactiver les notifications',
    'Mute notifications coming soon': 'Désactiver les notifications bientôt disponible',
  },
};
